module Paths 
    let ``base`` = "/"
    let home = "/home"
    let index = "/index"
    let ``qr-generator`` = "/qr-generator"
    let sitemap = "/sitemap"
    let about = "/about"
    let experimental = "/experimental"
    let articles = "/articles"
    let ``license-generator`` = "/license-generator"
    let ``dev-random`` = "/dev/random"
    let ``Jonny's Sober Rants`` = "/rants"
    let ``all-programming-links`` = "/all-programming-links"
    let ``all-fun-links`` = "/all-fun-links"
    let ``portfolio-balancer`` = "/portfolio-balancer"