module Paths 
    let home = "/home"
    let ``qr-generator`` = "/qr-generator"
    let index = "/index"
    let resume = "/resume"
    let about = "/about"
    let experimental = "/experimental"
    let ``license-generator`` = "/license-generator"
    let ``dev-random`` = "/dev/random"
    let ``Jonny's Sober Rants`` = "/rants"