module Paths 
    let home = "/"
    let ``qr-generator`` = "/qr-generator"
    let index = "/index"
    let resume = "/resume"
    let about = "/about"
    let experimental = "/experimental"
    let ``license-generator`` = "/license-generator"
    let ``dev-random`` = "/dev/random"
    let ``Jonny's Sober Rants`` = "/rants"
    let ``all-programming-links`` = "/all-programming-links"
    let ``all-fun-links`` = "/all-fun-links"