export const actionsEnums = {
	incr: 'INCREMENT',
	decr: 'DECREMENT',
	updateUserProfileColour: 'UPDATE_USERPROFILE_FAVOURITE_COLOUR',
	MEMBER_REQUEST: 'MEMBER_REQUEST',
	MEMBER_REQUEST_COMPLETED: 'MEMEMBER_REQUEST_COMPLETED',
};
