[project]
name = "data-ingestion-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]",
    
    "ultralytics",
    "numpy",
    "opencv-python-headless",
    "influxdb3-python",
    "pandas",
    "gpiozero"
]

[project.optional-dependencies]
tooling = ["pyright"]

[tool.pyright]
include = ["./"]
exclude = [
    "**/__pycache__"
]